* dropbox

Follow command line instructions from:
https://www.dropbox.com/install?os=lnx

To install dropbox-cli:

#+BEGIN_EXAMPLE
mkdir -p ~/bin
cd ~/bin
wget https://www.dropbox.com/download?dl=packages/dropbox.py
mv dropbox.py dropbox
chmod +x dropbox
#+END_EXAMPLE

* emacs 24

Install required packages:

#+BEGIN_EXAMPLE
yum install libXpm-devel libtiff-devel giflib-devel
#+END_EXAMPLE

* cuda

Reference:
  https://access.redhat.com/site/solutions/64300

** /etc/ld.so.conf.d/cuda.conf

#+BEGIN_EXAMPLE
/usr/local/cuda/lib64
/usr/local/cuda/lib
#+END_EXAMPLE

** /etc/profile.d/cuda.sh

#+BEGIN_EXAMPLE
export PATH=/usr/local/cuda/bin:${PATH}
#+END_EXAMPLE

** blacklist nouveau

I only need the second line.  The CUDA installed adds the blacklist.

#+BEGIN_EXAMPLE
echo -e "\nblacklist nouveau" >> /etc/modprobe.d/blacklist.conf                                                                                                                                              
dracut -f /boot/initramfs-`rpm -qa kernel --queryformat "%{PROVIDEVERSION}.%{ARCH}\n" | tail -1`.img `rpm -qa kernel --queryformat "%{PROVIDEVERSION}.%{ARCH}\n" | tail -1`
#+END_EXAMPLE
** run nvidia-xconfig after installing driver

* disable virt-who

use System>Administration>Services

* python

Packages to install
- tk-devel
- gdbm-devel
- xz-devel
- xz
- xz-libs

#+BEGIN_EXAMPLE
wget http://www.python.org/ftp/python/3.3.1/Python-3.3.1.tar.xz
tar Jxvf Python-3.3.1.tar.xz
cd Python-3.3.1/
./configure --prefix=/opt/python-3.3.1
#+END_EXAMPLE
* flash

- Installed from repoforge.
- youtube videos have blue tint

** solution

reference:
  http://blog.satisheerpini.net/2012/04/fixed-blue-tint-on-youtube-videos-flash.html

[Fixed] Blue Tint on Youtube videos (flash problem) on Centos 6.x

I have the adobe flash plugin from the adobe repository with the following
version installed on my laptop running Centos :


flash-plugin.x86_64                    11.2.202.233-release    @adobe-linux-x86_64

Since the last update, the videos on Youtube have mostly had a blue tint and
less often a pale orange shade. After a couple of days of not trying to fix it
(thanks to the hectic semester) I guessed this was a problem with flash or
something to do with how flash uses the GPU, since those are the only two
pieces of proprietary software on my laptop (and thus would be expected to be
fixed rather slow for a problem so evident).  Finally, a little googling around
showed this post on the Arch Linux forums :
https://bbs.archlinux.org/viewtopic.php?pid=1084648

I just followed whatever was mentioned there, and the flash plugin looks far
more stable now. Here are the steps I followed on my Centos 6.x machine :

1. Created the file /etc/adobe/mms.cfg and added the following contents : 

#Hardware video decoding
EnableLinuxHWVideoDecode=1
OverrideGPUValidation=true

2. Added the following line at the beginning of  /etc/X11/xinit/xinitrc-common

export VDPAU_NVIDIA_NO_OVERLAY=1

You will need root permissions for both of the above, an alternative for the
second step can be adding the same line to the user specific xinitrc file
(~/.xinitrc). I logged out and logged in again after the changes, the blue tint
is gone and the flash plugin itself is far more stable than before. As
suggested in the thread on the arch linux forums, it might be a good idea to
try a free alternative to the adobe flash player plugin if possible.

PS : 
1. I run Centos 6.x on my Dell E6410, which has a NVIDIA NVS 3100M gpu.
2. It is just amazing the thread which showed up was on the arch linux forums, Arch Linux continues to amaze me.
* x-tile

- Download from:
  http://www.giuspen.com/x-tile/

- extract in build directory

- Modify code:

mostly replace references to =/usr/= with =/usr/local= for a safe install.

#+BEGIN_EXAMPLE
diff --git a/build/scripts-2.6/x-tile b/build/scripts-2.6/x-tile
index c1d176b..fbe7287 100755
--- a/build/scripts-2.6/x-tile
+++ b/build/scripts-2.6/x-tile
@@ -1,4 +1,4 @@
-#!/usr/bin/python
+#!/usr/bin/env python
 # -*- coding: UTF-8 -*-
 """X Tile main module"""
 
@@ -31,7 +31,7 @@ import gtk, gconf
 import __builtin__
 
 if os.path.isfile('modules/globs.py'): MODULES_PATH = 'modules/'
-else: MODULES_PATH = '/usr/share/x-tile/modules/'
+else: MODULES_PATH = '/usr/local/share/x-tile/modules/'
 sys.path.append(MODULES_PATH)
 import cons, globs, core
 
diff --git a/modules/cons.py b/modules/cons.py
index def37f9..f70ae7a 100644
--- a/modules/cons.py
+++ b/modules/cons.py
@@ -33,8 +33,8 @@ if os.path.isdir("glade"):
     GLADE_PATH = os.path.join(os.getcwd(), "glade/")
     LOCALE_PATH = "locale/"
 else:
-    GLADE_PATH = "/usr/share/x-tile/glade/"
-    LOCALE_PATH = "/usr/share/locale/"
+    GLADE_PATH = "/usr/local/share/x-tile/glade/"
+    LOCALE_PATH = "/usr/local/share/locale/"
 
 AVAILABLE_LANGS = ['default', 'cs', 'de', 'en', 'es_AR', 'fr', 'it', 'pl', 'ru', 'zh_CN', 'zh_TW']
 
diff --git a/modules/cons.pyc b/modules/cons.pyc
index 9d75ee3..dd89f88 100644
Binary files a/modules/cons.pyc and b/modules/cons.pyc differ
diff --git a/setup.py b/setup.py
index a5b8d60..d6c475e 100644
--- a/setup.py
+++ b/setup.py
@@ -1,6 +1,6 @@
 #!/usr/bin/env python
 
-# for linux install: "python setup.py install --prefix=/usr --exec-prefix=/usr -f"
+# for linux install: "python setup.py install --prefix=/usr/local --exec-prefix=/usr/local -f"
 
 from distutils.core import setup
 from distutils.dist import Distribution
diff --git a/x-tile b/x-tile
index 9cd6d34..fbe7287 100755
--- a/x-tile
+++ b/x-tile
@@ -31,7 +31,7 @@ import gtk, gconf
 import __builtin__
 
 if os.path.isfile('modules/globs.py'): MODULES_PATH = 'modules/'
-else: MODULES_PATH = '/usr/share/x-tile/modules/'
+else: MODULES_PATH = '/usr/local/share/x-tile/modules/'
 sys.path.append(MODULES_PATH)
 import cons, globs, core
#+END_EXAMPLE

- Install

#+BEGIN_EXAMPLE
sudo python setup.py install --prefix=/usr/local --exec-prefix=/usr/local -f
#+END_EXAMPLE

- Tell gnome to start x-tile on startup
* enable EPEL repository

Reference:
  http://fedoraproject.org/wiki/EPEL

#+BEGIN_SRC sh
sudo rpm -Uvh http://mirror.cc.columbia.edu/pub/linux/epel/6/i386/epel-release-6-8.noarch.rpm
#+END_SRC

Note: may have to update the mirror
