* disable dashboard

Command to disable:

#+BEGIN_SRC sh
defaults write com.apple.dashboard mcx-disabled -bool true && killall Dock
#+END_SRC

Command to enable:

#+begin_src sh
defaults write com.apple.dashboard mcx-disabled -bool false && killall Dock
#+end_src

Reference:
http://superuser.com/questions/314474/how-to-disable-the-mac-os-x-dashboard
http://lifehacker.com/182657/how-to-turn-mac-os-x-dashboard-off

* alias emacs in /Applications

=brew= installs emacs to:
  /usr/local/Cellar/emacs/24.2

The easiest way to get spotlight to pick up emacs for launching is to
create a Mac OS X alias to:
  /usr/local/Cellar/emacs/24.2/Emacs.app
in:
  /Applications

Reference:
- http://apple.stackexchange.com/questions/23653/can-i-make-a-symlink-to-a-app-folder-in-applications-directory-show-up-in-spo

* window tiling apps

I like SizeUp more.

** SizeUp

- http://www.irradiatedsoftware.com/sizeup/index.html
- purchased
- license is in emacs

** Breeze

- http://autumnapps.com/breeze/index.html
- purchase through app store

* create link from /home to /Users

First edit =/etc/auto_master= and comment out the home line:

#+begin_src sh
sudo emacs /etc/auto_master
#+end_src

#+begin_example
#
# Automounter master map
#
+auto_master		# Use directory service
/net			-hosts		-nobrowse,hidefromfinder,nosuid
#/home			auto_home	-nobrowse,hidefromfinder
/Network/Servers	-fstab
/-			-static
#+end_example

Now, reboot.  Then create the link:

#+begin_src sh
sudo ln -s /Users /home
#+end_src

Note: you may have to delete /home first.

* modify /etc/paths

The command =brew doctor= recommends putting =/usr/local/bin= before
=/usr/bin= in =/etc/paths=.  This means that brew commands will take
precedence over system files.

* homebrew and /usr/local

Homebrew appears to require that the user be the owner of =/usr/local/=.  This
fixed a problem with using =brew= to install =git=.

I ran this command:

#+BEGIN_EXAMPLE
sudo chown -R nwh /usr/local
#+END_EXAMPLE

* command line trash

I use a package called =rmtrash= that exists in the homebrew system.  I alias
to =tp= for compatibility with my linux setup.

#+BEGIN_SRC sh
brew install rmtrash
alias tp="rmtrash"
#+END_SRC

* Terminal.app solarized color scheme

See:
https://github.com/tomislav/osx-lion-terminal.app-colors-solarized

Just download the files and import into the Terminal.app profile preferences.
* Eclipse.app in high resolution

To enable a retina rendered Eclipse

From: https://bugs.eclipse.org/bugs/show_bug.cgi?id=382972

Here's the workaround:

Do "Show package contents" on the Eclipse.app. Edit Contents/Info.plist using
your favorite text editor. Just above

#+BEGIN_EXAMPLE
</dict>
</plist>
#+END_EXAMPLE

Place this:

#+BEGIN_EXAMPLE
<key>NSHighResolutionCapable</key>
<true/>
#+END_EXAMPLE

Then, make a copy of the app so that OSX will notice the change. Now, the info
window will not show "Open in Low Resolution" as checked. Launch Eclipse and
enjoy your new retina awesomeness.


reference:
  http://apple.stackexchange.com/questions/53717/how-does-eclipse-work-on-new-retina-macbook-pros
